const express = require("express");
const route = express.Router();

route.get("/Categorised", (req, res) => {
  const categoriesProducts = [
    // ==============================
    // NEW ARRIVALS (10 products)
    // ==============================
    {
      id: 1,
      name: "Premium Wireless Headphones",
      title: "Premium Wireless Headphones",
      brand: "AudioTech",
      price: 299.99,
      currency: "USD",
      rating: 4.8,
      reviews: 342,
      description: "Latest noise-cancelling wireless headphones with 30-hour battery life",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
        "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500"
      ],
      category: "newarrivals",
      categories: ["newarrivals", "electronics"],
      tags: ["new", "wireless", "audio", "headphones"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 120,
      stock: 45,
      createdAt: "2024-12-01",
      slug: "premium-wireless-headphones"
    },
    {
      id: 2,
      name: "Smart Fitness Watch",
      title: "Smart Fitness Watch",
      brand: "FitPro",
      price: 199.99,
      currency: "USD",
      rating: 4.6,
      reviews: 189,
      description: "Advanced fitness tracker with heart rate monitor and GPS",
      image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
      images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "accessories"],
      tags: ["new", "fitness", "smartwatch", "wearable"],
      onSale: true,
      isNew: true,
      isExclusive: false,
      sales: 85,
      stock: 30,
      createdAt: "2024-12-05",
      slug: "smart-fitness-watch"
    },
    {
      id: 3,
      name: "Foldable Electric Scooter",
      title: "Foldable Electric Scooter",
      brand: "UrbanRide",
      price: 599.99,
      currency: "USD",
      rating: 4.5,
      reviews: 267,
      description: "Portable electric scooter with 25-mile range",
      image: "https://images.unsplash.com/photo-1577493340880-5c61f6faa575?w=500",
      images: ["https://images.unsplash.com/photo-1577493340880-5c61f6faa575?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "electronics"],
      tags: ["new", "electric", "scooter", "transport"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 45,
      stock: 20,
      createdAt: "2024-12-10",
      slug: "foldable-electric-scooter"
    },
    {
      id: 4,
      name: "4K Action Camera",
      title: "4K Action Camera",
      brand: "AdventureCam",
      price: 349.99,
      currency: "USD",
      rating: 4.7,
      reviews: 178,
      description: "Waterproof action camera with 4K video recording",
      image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500",
      images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "electronics"],
      tags: ["new", "camera", "action", "4k"],
      onSale: true,
      isNew: true,
      isExclusive: false,
      sales: 65,
      stock: 35,
      createdAt: "2024-12-03",
      slug: "4k-action-camera"
    },
    {
      id: 5,
      name: "Ergonomic Office Chair",
      title: "Ergonomic Office Chair",
      brand: "WorkComfort",
      price: 459.99,
      currency: "USD",
      rating: 4.9,
      reviews: 423,
      description: "Lumbar support office chair with adjustable features",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500",
      images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "homeliving"],
      tags: ["new", "office", "chair", "ergonomic"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 90,
      stock: 25,
      createdAt: "2024-12-07",
      slug: "ergonomic-office-chair"
    },
    {
      id: 6,
      name: "Smart Home Hub",
      title: "Smart Home Hub",
      brand: "HomeConnect",
      price: 129.99,
      currency: "USD",
      rating: 4.4,
      reviews: 89,
      description: "Central control hub for smart home devices",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500",
      images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "electronics"],
      tags: ["new", "smart", "home", "automation"],
      onSale: false,
      isNew: true,
      isExclusive: false,
      sales: 40,
      stock: 50,
      createdAt: "2024-12-12",
      slug: "smart-home-hub"
    },
    {
      id: 7,
      name: "UV Sanitizer Box",
      title: "UV Sanitizer Box",
      brand: "CleanTech",
      price: 79.99,
      currency: "USD",
      rating: 4.3,
      reviews: 156,
      description: "UV light sanitizer for phones, keys, and small items",
      image: "https://images.unsplash.com/photo-1580338450113-2b5d9b7e5e0f?w=500",
      images: ["https://images.unsplash.com/photo-1580338450113-2b5d9b7e5e0f?w=500"],
      category: "newarrivals",
      categories: ["newarrivals"],
      tags: ["new", "sanitizer", "uv", "clean"],
      onSale: true,
      isNew: true,
      isExclusive: false,
      sales: 75,
      stock: 60,
      createdAt: "2024-12-08",
      slug: "uv-sanitizer-box"
    },
    {
      id: 8,
      name: "Electric Kettle with Temperature Control",
      title: "Electric Kettle with Temperature Control",
      brand: "BrewPerfect",
      price: 89.99,
      currency: "USD",
      rating: 4.6,
      reviews: 231,
      description: "Precision temperature control electric kettle",
      image: "https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?w=500",
      images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "homeliving"],
      tags: ["new", "kettle", "electric", "kitchen"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 110,
      stock: 40,
      createdAt: "2024-12-04",
      slug: "electric-kettle"
    },
    {
      id: 9,
      name: "Wireless Charging Pad",
      title: "Wireless Charging Pad",
      brand: "ChargeFast",
      price: 49.99,
      currency: "USD",
      rating: 4.5,
      reviews: 312,
      description: "15W fast wireless charging pad for smartphones",
      image: "https://images.unsplash.com/photo-1581291518633-83b4eb8d87c1?w=500",
      images: ["https://images.unsplash.com/photo-1581291518633-83b4eb8d87c1?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "electronics"],
      tags: ["new", "wireless", "charger", "fast"],
      onSale: true,
      isNew: true,
      isExclusive: false,
      sales: 180,
      stock: 80,
      createdAt: "2024-12-09",
      slug: "wireless-charging-pad"
    },
    {
      id: 10,
      name: "Portable Air Purifier",
      title: "Portable Air Purifier",
      brand: "AirPure",
      price: 159.99,
      currency: "USD",
      rating: 4.7,
      reviews: 189,
      description: "Compact HEPA air purifier for rooms up to 300 sq ft",
      image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500",
      images: ["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500"],
      category: "newarrivals",
      categories: ["newarrivals", "homeliving"],
      tags: ["new", "air", "purifier", "health"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 65,
      stock: 30,
      createdAt: "2024-12-06",
      slug: "portable-air-purifier"
    },

    // ==============================
    // CLOTHING (10 products)
    // ==============================
    {
      id: 11,
      name: "Premium Cotton T-Shirt",
      title: "Premium Cotton T-Shirt",
      brand: "UrbanWear",
      price: 39.99,
      currency: "USD",
      rating: 4.5,
      reviews: 456,
      description: "100% organic cotton t-shirt with premium finish",
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
      images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["tshirt", "cotton", "casual", "basic"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 320,
      stock: 150,
      createdAt: "2024-10-15",
      slug: "premium-cotton-tshirt"
    },
    {
      id: 12,
      name: "Denim Jacket",
      title: "Classic Denim Jacket",
      brand: "DenimCo",
      price: 89.99,
      currency: "USD",
      rating: 4.7,
      reviews: 231,
      description: "Vintage wash denim jacket with distressed details",
      image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
      images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["denim", "jacket", "vintage", "casual"],
      onSale: true,
      isNew: false,
      isExclusive: true,
      sales: 150,
      stock: 45,
      createdAt: "2024-09-20",
      slug: "denim-jacket"
    },
    {
      id: 13,
      name: "Wool Blend Sweater",
      title: "Warm Wool Blend Sweater",
      brand: "CozyKnits",
      price: 75.50,
      currency: "USD",
      rating: 4.4,
      reviews: 178,
      description: "Soft wool blend sweater for cold weather",
      image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500",
      images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["sweater", "wool", "winter", "knit"],
      onSale: false,
      isNew: true,
      isExclusive: false,
      sales: 95,
      stock: 60,
      createdAt: "2024-11-10",
      slug: "wool-blend-sweater"
    },
    {
      id: 14,
      name: "Linen Button-Down Shirt",
      title: "Linen Button-Down Shirt",
      brand: "NaturalFabrics",
      price: 64.99,
      currency: "USD",
      rating: 4.6,
      reviews: 267,
      description: "Breathable linen shirt for warm weather",
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500",
      images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["shirt", "linen", "summer", "casual"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 120,
      stock: 70,
      createdAt: "2024-08-12",
      slug: "linen-shirt"
    },
    {
      id: 15,
      name: "Athletic Joggers",
      title: "Athletic Joggers",
      brand: "ActiveWear",
      price: 54.99,
      currency: "USD",
      rating: 4.3,
      reviews: 189,
      description: "Comfortable athletic joggers with moisture-wicking fabric",
      image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=500",
      images: ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["joggers", "athletic", "sport", "pants"],
      onSale: false,
      isNew: false,
      isExclusive: true,
      sales: 85,
      stock: 90,
      createdAt: "2024-10-05",
      slug: "athletic-joggers"
    },
    {
      id: 16,
      name: "Leather Moto Jacket",
      title: "Leather Moto Jacket",
      brand: "RebelStyle",
      price: 249.99,
      currency: "USD",
      rating: 4.8,
      reviews: 156,
      description: "Genuine leather motorcycle jacket",
      image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
      images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["leather", "jacket", "moto", "biker"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 45,
      stock: 25,
      createdAt: "2024-11-25",
      slug: "leather-moto-jacket"
    },
    {
      id: 17,
      name: "Cashmere Scarf",
      title: "Luxury Cashmere Scarf",
      brand: "WinterLux",
      price: 129.99,
      currency: "USD",
      rating: 4.9,
      reviews: 89,
      description: "100% pure cashmere winter scarf",
      image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500",
      images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500"],
      category: "clothing",
      categories: ["clothing", "accessories"],
      tags: ["scarf", "cashmere", "winter", "luxury"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 60,
      stock: 40,
      createdAt: "2024-09-30",
      slug: "cashmere-scarf"
    },
    {
      id: 18,
      name: "Chino Pants",
      title: "Classic Chino Pants",
      brand: "SmartCasual",
      price: 69.99,
      currency: "USD",
      rating: 4.5,
      reviews: 312,
      description: "Versatile chino pants for work or casual",
      image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500",
      images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["pants", "chino", "casual", "work"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 210,
      stock: 110,
      createdAt: "2024-08-20",
      slug: "chino-pants"
    },
    {
      id: 19,
      name: "Hooded Sweatshirt",
      title: "Hooded Sweatshirt",
      brand: "ComfortZone",
      price: 49.99,
      currency: "USD",
      rating: 4.4,
      reviews: 423,
      description: "Cozy fleece hoodie for everyday wear",
      image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500",
      images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["hoodie", "sweatshirt", "casual", "fleece"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 180,
      stock: 85,
      createdAt: "2024-10-25",
      slug: "hooded-sweatshirt"
    },
    {
      id: 20,
      name: "Evening Dress",
      title: "Elegant Evening Dress",
      brand: "NightElegance",
      price: 189.99,
      currency: "USD",
      rating: 4.7,
      reviews: 78,
      description: "Floor-length evening dress for special occasions",
      image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500",
      images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500"],
      category: "clothing",
      categories: ["clothing"],
      tags: ["dress", "evening", "formal", "elegant"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 35,
      stock: 20,
      createdAt: "2024-11-20",
      slug: "evening-dress"
    },

    // ==============================
    // FOOTWEAR (10 products)
    // ==============================
    {
      id: 21,
      name: "Running Sneakers",
      title: "Performance Running Sneakers",
      brand: "RunFast",
      price: 129.99,
      currency: "USD",
      rating: 4.8,
      reviews: 512,
      description: "Lightweight running shoes with advanced cushioning",
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
      images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["sneakers", "running", "sports", "shoes"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 420,
      stock: 80,
      createdAt: "2024-08-25",
      slug: "running-sneakers"
    },
    {
      id: 22,
      name: "Leather Boots",
      title: "Classic Leather Boots",
      brand: "LeatherCraft",
      price: 159.99,
      currency: "USD",
      rating: 4.9,
      reviews: 267,
      description: "Handcrafted leather boots with durable sole",
      image: "https://images.unsplash.com/photo-1608256246200-53e6355f616f?w=500",
      images: ["https://images.unsplash.com/photo-1608256246200-53e6355f616f?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["boots", "leather", "classic", "durable"],
      onSale: true,
      isNew: false,
      isExclusive: true,
      sales: 180,
      stock: 35,
      createdAt: "2024-09-05",
      slug: "leather-boots"
    },
    {
      id: 23,
      name: "Casual Slip-Ons",
      title: "Casual Slip-Ons",
      brand: "EasyWear",
      price: 59.99,
      currency: "USD",
      rating: 4.3,
      reviews: 189,
      description: "Comfortable slip-on shoes for everyday use",
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500",
      images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["slipons", "casual", "comfort", "shoes"],
      onSale: false,
      isNew: true,
      isExclusive: false,
      sales: 95,
      stock: 65,
      createdAt: "2024-11-15",
      slug: "casual-slip-ons"
    },
    {
      id: 24,
      name: "Hiking Boots",
      title: "Waterproof Hiking Boots",
      brand: "TrailMaster",
      price: 139.99,
      currency: "USD",
      rating: 4.7,
      reviews: 234,
      description: "Waterproof hiking boots with ankle support",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=500",
      images: ["https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["hiking", "boots", "outdoor", "waterproof"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 120,
      stock: 45,
      createdAt: "2024-09-30",
      slug: "hiking-boots"
    },
    {
      id: 25,
      name: "Formal Dress Shoes",
      title: "Formal Dress Shoes",
      brand: "ElegantStep",
      price: 179.99,
      currency: "USD",
      rating: 4.6,
      reviews: 156,
      description: "Polished leather dress shoes for formal occasions",
      image: "https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=500",
      images: ["https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["formal", "dress", "shoes", "leather"],
      onSale: false,
      isNew: false,
      isExclusive: true,
      sales: 75,
      stock: 30,
      createdAt: "2024-10-10",
      slug: "formal-dress-shoes"
    },
    {
      id: 26,
      name: "Basketball Shoes",
      title: "Performance Basketball Shoes",
      brand: "JumpHigh",
      price: 149.99,
      currency: "USD",
      rating: 4.8,
      reviews: 289,
      description: "High-top basketball shoes with ankle support",
      image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500",
      images: ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["basketball", "sports", "athletic", "shoes"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 160,
      stock: 50,
      createdAt: "2024-08-15",
      slug: "basketball-shoes"
    },
    {
      id: 27,
      name: "Sandals",
      title: "Comfortable Sandals",
      brand: "SummerWalk",
      price: 44.99,
      currency: "USD",
      rating: 4.2,
      reviews: 178,
      description: "Breathable sandals for summer days",
      image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=500",
      images: ["https://images.unsplash.com/photo-1560343090-f0409e92791a?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["sandals", "summer", "comfort", "casual"],
      onSale: false,
      isNew: true,
      isExclusive: false,
      sales: 90,
      stock: 75,
      createdAt: "2024-11-05",
      slug: "comfortable-sandals"
    },
    {
      id: 28,
      name: "Platform Sneakers",
      title: "Platform Sneakers",
      brand: "UrbanHeight",
      price: 89.99,
      currency: "USD",
      rating: 4.5,
      reviews: 123,
      description: "Fashion platform sneakers with bold design",
      image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=500",
      images: ["https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["platform", "sneakers", "fashion", "urban"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 60,
      stock: 35,
      createdAt: "2024-11-25",
      slug: "platform-sneakers"
    },
    {
      id: 29,
      name: "Trail Running Shoes",
      title: "Trail Running Shoes",
      brand: "MountainRun",
      price: 119.99,
      currency: "USD",
      rating: 4.6,
      reviews: 156,
      description: "Grip-focused trail running shoes",
      image: "https://images.unsplash.com/photo-1600688640154-9619e002df30?w=500",
      images: ["https://images.unsplash.com/photo-1600688640154-9619e002df30?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["trail", "running", "outdoor", "grip"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 85,
      stock: 40,
      createdAt: "2024-09-20",
      slug: "trail-running-shoes"
    },
    {
      id: 30,
      name: "Slides",
      title: "Comfort Slides",
      brand: "RelaxFeet",
      price: 34.99,
      currency: "USD",
      rating: 4.1,
      reviews: 267,
      description: "Soft foam slides for indoor/outdoor use",
      image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=500",
      images: ["https://images.unsplash.com/photo-1560343090-f0409e92791a?w=500"],
      category: "footwear",
      categories: ["footwear"],
      tags: ["slides", "comfort", "casual", "indoor"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 210,
      stock: 95,
      createdAt: "2024-08-10",
      slug: "comfort-slides"
    },

    // ==============================
    // ACCESSORIES (10 products)
    // ==============================
    {
      id: 31,
      name: "Minimalist Watch",
      title: "Minimalist Stainless Steel Watch",
      brand: "TimeCraft",
      price: 249.99,
      currency: "USD",
      rating: 4.7,
      reviews: 189,
      description: "Elegant minimalist watch with sapphire crystal",
      image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=500",
      images: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["watch", "minimalist", "stainless", "elegant"],
      onSale: false,
      isNew: false,
      isExclusive: true,
      sales: 95,
      stock: 25,
      createdAt: "2024-10-30",
      slug: "minimalist-watch"
    },
    {
      id: 32,
      name: "Leather Messenger Bag",
      title: "Professional Leather Messenger Bag",
      brand: "UrbanGear",
      price: 189.99,
      currency: "USD",
      rating: 4.6,
      reviews: 143,
      description: "Genuine leather messenger bag for professionals",
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
      images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["bag", "leather", "messenger", "professional"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 75,
      stock: 40,
      createdAt: "2024-09-15",
      slug: "leather-messenger-bag"
    },
    {
      id: 33,
      name: "Aviator Sunglasses",
      title: "Classic Aviator Sunglasses",
      brand: "SunShield",
      price: 129.99,
      currency: "USD",
      rating: 4.5,
      reviews: 267,
      description: "Polarized aviator sunglasses with UV protection",
      image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500",
      images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["sunglasses", "aviator", "polarized", "uv"],
      onSale: false,
      isNew: true,
      isExclusive: false,
      sales: 120,
      stock: 55,
      createdAt: "2024-11-20",
      slug: "aviator-sunglasses"
    },
    {
      id: 34,
      name: "Silver Necklace",
      title: "Silver Necklace",
      brand: "JewelCraft",
      price: 89.99,
      currency: "USD",
      rating: 4.8,
      reviews: 189,
      description: "Sterling silver necklace with pendant",
      image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500",
      images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["necklace", "silver", "jewelry", "pendant"],
      onSale: true,
      isNew: false,
      isExclusive: true,
      sales: 65,
      stock: 30,
      createdAt: "2024-10-05",
      slug: "silver-necklace"
    },
    {
      id: 35,
      name: "Leather Wallet",
      title: "Genuine Leather Wallet",
      brand: "LeatherWorks",
      price: 59.99,
      currency: "USD",
      rating: 4.4,
      reviews: 312,
      description: "Compact leather wallet with multiple card slots",
      image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500",
      images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["wallet", "leather", "compact", "cards"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 180,
      stock: 85,
      createdAt: "2024-08-30",
      slug: "leather-wallet"
    },
    {
      id: 36,
      name: "Smart Ring",
      title: "Smart Ring with Fitness Tracking",
      brand: "WearTech",
      price: 199.99,
      currency: "USD",
      rating: 4.3,
      reviews: 89,
      description: "Smart ring that tracks activity and sleep",
      image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500",
      images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500"],
      category: "accessories",
      categories: ["accessories", "electronics"],
      tags: ["smart", "ring", "fitness", "tracking"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 40,
      stock: 25,
      createdAt: "2024-12-01",
      slug: "smart-ring"
    },
    {
      id: 37,
      name: "Canvas Backpack",
      title: "Canvas Backpack",
      brand: "EverydayCarry",
      price: 79.99,
      currency: "USD",
      rating: 4.6,
      reviews: 234,
      description: "Durable canvas backpack with laptop compartment",
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
      images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["backpack", "canvas", "laptop", "durable"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 95,
      stock: 45,
      createdAt: "2024-09-25",
      slug: "canvas-backpack"
    },
    {
      id: 38,
      name: "Silk Tie",
      title: "Silk Tie",
      brand: "FormalAttire",
      price: 49.99,
      currency: "USD",
      rating: 4.5,
      reviews: 156,
      description: "100% silk tie for formal occasions",
      image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500",
      images: ["https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["tie", "silk", "formal", "business"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 75,
      stock: 60,
      createdAt: "2024-10-20",
      slug: "silk-tie"
    },
    {
      id: 39,
      name: "Belt",
      title: "Genuine Leather Belt",
      brand: "LeatherCraft",
      price: 44.99,
      currency: "USD",
      rating: 4.4,
      reviews: 267,
      description: "Classic leather belt with brass buckle",
      image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500",
      images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["belt", "leather", "classic", "brass"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 120,
      stock: 70,
      createdAt: "2024-09-10",
      slug: "leather-belt"
    },
    {
      id: 40,
      name: "Earrings",
      title: "Gold Earrings",
      brand: "GoldStyle",
      price: 129.99,
      currency: "USD",
      rating: 4.7,
      reviews: 178,
      description: "14k gold earrings with diamond accents",
      image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500",
      images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500"],
      category: "accessories",
      categories: ["accessories"],
      tags: ["earrings", "gold", "diamond", "jewelry"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 50,
      stock: 35,
      createdAt: "2024-11-15",
      slug: "gold-earrings"
    },

    // ==============================
    // HOME & LIVING (10 products)
    // ==============================
    {
      id: 41,
      name: "Ceramic Table Lamp",
      title: "Modern Ceramic Table Lamp",
      brand: "HomeGlow",
      price: 89.99,
      currency: "USD",
      rating: 4.5,
      reviews: 98,
      description: "Handmade ceramic table lamp with linen shade",
      image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500",
      images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["lamp", "ceramic", "home", "decor"],
      onSale: false,
      isNew: true,
      isExclusive: false,
      sales: 45,
      stock: 30,
      createdAt: "2024-11-20",
      slug: "ceramic-table-lamp"
    },
    {
      id: 42,
      name: "Organic Cotton Bed Sheets",
      title: "Luxury Organic Cotton Bed Sheets",
      brand: "SleepWell",
      price: 129.99,
      currency: "USD",
      rating: 4.8,
      reviews: 167,
      description: "400 thread count organic cotton bed sheets set",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500",
      images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["bedsheets", "cotton", "bedding", "organic"],
      onSale: true,
      isNew: false,
      isExclusive: true,
      sales: 120,
      stock: 50,
      createdAt: "2024-10-10",
      slug: "organic-cotton-bed-sheets"
    },
    {
      id: 43,
      name: "Wooden Coffee Table",
      title: "Solid Wood Coffee Table",
      brand: "NaturalWood",
      price: 299.99,
      currency: "USD",
      rating: 4.7,
      reviews: 78,
      description: "Handcrafted solid wood coffee table",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500",
      images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["table", "wood", "furniture", "coffee"],
      onSale: false,
      isNew: false,
      isExclusive: true,
      sales: 35,
      stock: 15,
      createdAt: "2024-09-15",
      slug: "wooden-coffee-table"
    },
    {
      id: 44,
      name: "Wall Art Canvas",
      title: "Abstract Wall Art Canvas",
      brand: "ArtisticHome",
      price: 149.99,
      currency: "USD",
      rating: 4.6,
      reviews: 89,
      description: "Large abstract painting on canvas",
      image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=500",
      images: ["https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["art", "canvas", "wall", "decor"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 60,
      stock: 25,
      createdAt: "2024-10-25",
      slug: "wall-art-canvas"
    },
    {
      id: 45,
      name: "Ceramic Dinner Set",
      title: "Ceramic Dinner Set",
      brand: "TableStyle",
      price: 189.99,
      currency: "USD",
      rating: 4.8,
      reviews: 156,
      description: "12-piece ceramic dinner set for 4",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500",
      images: ["https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["dinnerware", "ceramic", "kitchen", "set"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 45,
      stock: 30,
      createdAt: "2024-11-30",
      slug: "ceramic-dinner-set"
    },
    {
      id: 46,
      name: "Area Rug",
      title: "Wool Area Rug",
      brand: "FloorComfort",
      price: 249.99,
      currency: "USD",
      rating: 4.5,
      reviews: 123,
      description: "Handwoven wool area rug 5x7 feet",
      image: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=500",
      images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["rug", "wool", "floor", "decor"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 55,
      stock: 20,
      createdAt: "2024-09-05",
      slug: "wool-area-rug"
    },
    {
      id: 47,
      name: "Throw Pillows Set",
      title: "Decorative Throw Pillows Set",
      brand: "CozyHome",
      price: 79.99,
      currency: "USD",
      rating: 4.4,
      reviews: 189,
      description: "Set of 4 decorative throw pillows",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500",
      images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["pillows", "decor", "comfort", "home"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 90,
      stock: 65,
      createdAt: "2024-10-15",
      slug: "throw-pillows-set"
    },
    {
      id: 48,
      name: "Smart Thermostat",
      title: "Smart Thermostat",
      brand: "HomeSmart",
      price: 199.99,
      currency: "USD",
      rating: 4.7,
      reviews: 267,
      description: "Wi-Fi enabled smart thermostat with app control",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500",
      images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500"],
      category: "homeliving",
      categories: ["homeliving", "electronics"],
      tags: ["thermostat", "smart", "home", "wifi"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 75,
      stock: 40,
      createdAt: "2024-11-25",
      slug: "smart-thermostat"
    },
    {
      id: 49,
      name: "Glass Vase",
      title: "Handblown Glass Vase",
      brand: "GlassArt",
      price: 69.99,
      currency: "USD",
      rating: 4.6,
      reviews: 89,
      description: "Handblown glass vase for floral arrangements",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500",
      images: ["https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["vase", "glass", "decor", "floral"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 40,
      stock: 35,
      createdAt: "2024-09-30",
      slug: "glass-vase"
    },
    {
      id: 50,
      name: "Kitchen Knife Set",
      title: "Professional Kitchen Knife Set",
      brand: "ChefTools",
      price: 159.99,
      currency: "USD",
      rating: 4.9,
      reviews: 234,
      description: "8-piece professional chef knife set",
      image: "https://images.unsplash.com/photo-1588666309990-d68f08e3d4c6?w=500",
      images: ["https://images.unsplash.com/photo-1588666309990-d68f08e3d4c6?w=500"],
      category: "homeliving",
      categories: ["homeliving"],
      tags: ["knife", "kitchen", "chef", "tools"],
      onSale: false,
      isNew: false,
      isExclusive: true,
      sales: 85,
      stock: 30,
      createdAt: "2024-10-05",
      slug: "kitchen-knife-set"
    },

    // ==============================
    // ELECTRONICS (10 products)
    // ==============================
    {
      id: 51,
      name: "Smartphone Pro",
      title: "Latest Smartphone Pro",
      brand: "TechGadget",
      price: 999.99,
      currency: "USD",
      rating: 4.9,
      reviews: 892,
      description: "Flagship smartphone with advanced camera system",
      image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500",
      images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["smartphone", "tech", "mobile", "camera"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 650,
      stock: 100,
      createdAt: "2024-11-25",
      slug: "smartphone-pro"
    },
    {
      id: 52,
      name: "Gaming Laptop",
      title: "High-Performance Gaming Laptop",
      brand: "GameMaster",
      price: 1499.99,
      currency: "USD",
      rating: 4.7,
      reviews: 421,
      description: "Powerful gaming laptop with RTX graphics",
      image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
      images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["laptop", "gaming", "computer", "rtx"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 230,
      stock: 40,
      createdAt: "2024-09-30",
      slug: "gaming-laptop"
    },
    {
      id: 53,
      name: "Wireless Earbuds",
      title: "True Wireless Earbuds",
      brand: "SoundFree",
      price: 149.99,
      currency: "USD",
      rating: 4.6,
      reviews: 567,
      description: "True wireless earbuds with charging case",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
      images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["earbuds", "wireless", "audio", "bluetooth"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 320,
      stock: 85,
      createdAt: "2024-10-20",
      slug: "wireless-earbuds"
    },
    {
      id: 54,
      name: "4K Smart TV",
      title: "55-inch 4K Smart TV",
      brand: "VisionTech",
      price: 699.99,
      currency: "USD",
      rating: 4.8,
      reviews: 389,
      description: "4K Ultra HD smart TV with streaming apps",
      image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500",
      images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["tv", "4k", "smart", "television"],
      onSale: true,
      isNew: false,
      isExclusive: true,
      sales: 180,
      stock: 35,
      createdAt: "2024-09-15",
      slug: "4k-smart-tv"
    },
    {
      id: 55,
      name: "Tablet",
      title: "10-inch Tablet",
      brand: "TabTech",
      price: 399.99,
      currency: "USD",
      rating: 4.5,
      reviews: 267,
      description: "10-inch tablet with stylus support",
      image: "https://images.unsplash.com/photo-1546054451-6f3c3a6b32fa?w=500",
      images: ["https://images.unsplash.com/photo-1546054451-6f3c3a6b32fa?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["tablet", "portable", "touch", "stylus"],
      onSale: false,
      isNew: true,
      isExclusive: false,
      sales: 120,
      stock: 50,
      createdAt: "2024-11-10",
      slug: "10-inch-tablet"
    },
    {
      id: 56,
      name: "Smart Speaker",
      title: "Smart Speaker with Voice Assistant",
      brand: "VoiceHome",
      price: 129.99,
      currency: "USD",
      rating: 4.4,
      reviews: 456,
      description: "Smart speaker with built-in voice assistant",
      image: "https://images.unsplash.com/photo-1543512214-318c7553f230?w=500",
      images: ["https://images.unsplash.com/photo-1543512214-318c7553f230?w=500"],
      category: "electronics",
      categories: ["electronics", "homeliving"],
      tags: ["speaker", "smart", "voice", "assistant"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 210,
      stock: 75,
      createdAt: "2024-10-05",
      slug: "smart-speaker"
    },
    {
      id: 57,
      name: "Gaming Console",
      title: "Next-Gen Gaming Console",
      brand: "GameBox",
      price: 499.99,
      currency: "USD",
      rating: 4.9,
      reviews: 789,
      description: "Next-generation gaming console with 4K gaming",
      image: "https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=500",
      images: ["https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["console", "gaming", "4k", "entertainment"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 350,
      stock: 60,
      createdAt: "2024-11-30",
      slug: "gaming-console"
    },
    {
      id: 58,
      name: "External SSD",
      title: "1TB External SSD",
      brand: "DataFast",
      price: 129.99,
      currency: "USD",
      rating: 4.7,
      reviews: 312,
      description: "High-speed 1TB external solid state drive",
      image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500",
      images: ["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["ssd", "storage", "external", "fast"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 180,
      stock: 90,
      createdAt: "2024-09-25",
      slug: "external-ssd"
    },
    {
      id: 59,
      name: "Monitor",
      title: "27-inch 4K Monitor",
      brand: "DisplayPro",
      price: 349.99,
      currency: "USD",
      rating: 4.6,
      reviews: 234,
      description: "27-inch 4K monitor with HDR support",
      image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500",
      images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["monitor", "4k", "display", "hdr"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 95,
      stock: 40,
      createdAt: "2024-10-15",
      slug: "4k-monitor"
    },
    {
      id: 60,
      name: "Drone",
      title: "4K Camera Drone",
      brand: "SkyView",
      price: 599.99,
      currency: "USD",
      rating: 4.8,
      reviews: 189,
      description: "4K camera drone with GPS and obstacle avoidance",
      image: "https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=500",
      images: ["https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=500"],
      category: "electronics",
      categories: ["electronics"],
      tags: ["drone", "camera", "4k", "gps"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 65,
      stock: 25,
      createdAt: "2024-11-20",
      slug: "4k-camera-drone"
    },

    // ==============================
    // BEAUTY (10 products)
    // ==============================
    {
      id: 61,
      name: "Vitamin C Serum",
      title: "Brightening Vitamin C Serum",
      brand: "SkinGlow",
      price: 49.99,
      currency: "USD",
      rating: 4.6,
      reviews: 289,
      description: "Antioxidant serum for bright and even skin tone",
      image: "https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500",
      images: ["https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["skincare", "serum", "vitaminc", "beauty"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 180,
      stock: 75,
      createdAt: "2024-11-15",
      slug: "vitamin-c-serum"
    },
    {
      id: 62,
      name: "Matte Lipstick Set",
      title: "Luxury Matte Lipstick Set",
      brand: "LipLuxe",
      price: 65.00,
      currency: "USD",
      rating: 4.8,
      reviews: 156,
      description: "Set of 6 long-lasting matte lipsticks",
      image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500",
      images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["makeup", "lipstick", "matte", "cosmetics"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 95,
      stock: 60,
      createdAt: "2024-10-05",
      slug: "matte-lipstick-set"
    },
    {
      id: 63,
      name: "Hyaluronic Acid Moisturizer",
      title: "Hyaluronic Acid Moisturizer",
      brand: "HydraSkin",
      price: 39.99,
      currency: "USD",
      rating: 4.7,
      reviews: 423,
      description: "Intense hydration moisturizer with hyaluronic acid",
      image: "https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500",
      images: ["https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["moisturizer", "skincare", "hydration", "acid"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 240,
      stock: 95,
      createdAt: "2024-09-20",
      slug: "hyaluronic-acid-moisturizer"
    },
    {
      id: 64,
      name: "Eyeshadow Palette",
      title: "Professional Eyeshadow Palette",
      brand: "ColorArt",
      price: 54.99,
      currency: "USD",
      rating: 4.5,
      reviews: 189,
      description: "16-color professional eyeshadow palette",
      image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500",
      images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["eyeshadow", "palette", "makeup", "color"],
      onSale: true,
      isNew: true,
      isExclusive: false,
      sales: 75,
      stock: 45,
      createdAt: "2024-11-25",
      slug: "eyeshadow-palette"
    },
    {
      id: 65,
      name: "Sunscreen SPF 50",
      title: "Mineral Sunscreen SPF 50",
      brand: "SunSafe",
      price: 29.99,
      currency: "USD",
      rating: 4.8,
      reviews: 567,
      description: "Broad spectrum mineral sunscreen",
      image: "https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500",
      images: ["https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["sunscreen", "spf", "protection", "skincare"],
      onSale: false,
      isNew: false,
      isExclusive: true,
      sales: 320,
      stock: 120,
      createdAt: "2024-08-15",
      slug: "sunscreen-spf-50"
    },
    {
      id: 66,
      name: "Face Mask Set",
      title: "Sheet Face Mask Set",
      brand: "SkinRefresh",
      price: 24.99,
      currency: "USD",
      rating: 4.4,
      reviews: 234,
      description: "Set of 8 different sheet face masks",
      image: "https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500",
      images: ["https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["mask", "sheet", "skincare", "set"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 120,
      stock: 65,
      createdAt: "2024-10-10",
      slug: "face-mask-set"
    },
    {
      id: 67,
      name: "Makeup Brush Set",
      title: "Professional Makeup Brush Set",
      brand: "BrushCraft",
      price: 49.99,
      currency: "USD",
      rating: 4.6,
      reviews: 178,
      description: "12-piece professional makeup brush set",
      image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500",
      images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["brushes", "makeup", "tools", "professional"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 85,
      stock: 50,
      createdAt: "2024-11-30",
      slug: "makeup-brush-set"
    },
    {
      id: 68,
      name: "Perfume",
      title: "Signature Perfume",
      brand: "ScentLux",
      price: 89.99,
      currency: "USD",
      rating: 4.7,
      reviews: 267,
      description: "Long-lasting signature fragrance",
      image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500",
      images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["perfume", "fragrance", "scent", "luxury"],
      onSale: false,
      isNew: false,
      isExclusive: false,
      sales: 150,
      stock: 70,
      createdAt: "2024-09-25",
      slug: "signature-perfume"
    },
    {
      id: 69,
      name: "Nail Polish Set",
      title: "Gel Nail Polish Set",
      brand: "NailStyle",
      price: 34.99,
      currency: "USD",
      rating: 4.3,
      reviews: 189,
      description: "Set of 8 gel nail polishes with top coat",
      image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500",
      images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["nail", "polish", "gel", "set"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 95,
      stock: 80,
      createdAt: "2024-10-30",
      slug: "nail-polish-set"
    },
    {
      id: 70,
      name: "Retinol Night Cream",
      title: "Anti-Aging Retinol Night Cream",
      brand: "AgeDefy",
      price: 69.99,
      currency: "USD",
      rating: 4.8,
      reviews: 312,
      description: "Retinol-infused night cream for anti-aging",
      image: "https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500",
      images: ["https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=500"],
      category: "beauty",
      categories: ["beauty"],
      tags: ["retinol", "antiaging", "nightcream", "skincare"],
      onSale: false,
      isNew: true,
      isExclusive: true,
      sales: 110,
      stock: 45,
      createdAt: "2024-11-20",
      slug: "retinol-night-cream"
    },

    // ==============================
    // SALE (10 products)
    // ==============================
    {
      id: 71,
      name: "Winter Coat",
      title: "Heavy Duty Winter Coat",
      brand: "WarmStyle",
      price: 199.99,
      originalPrice: 299.99,
      currency: "USD",
      rating: 4.7,
      reviews: 234,
      description: "Insulated winter coat with waterproof finish",
      image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=500",
      images: ["https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=500"],
      category: "sale",
      categories: ["sale", "clothing"],
      tags: ["coat", "winter", "sale", "waterproof"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 320,
      stock: 25,
      createdAt: "2024-08-15",
      slug: "winter-coat"
    },
    {
      id: 72,
      name: "Coffee Maker",
      title: "Automatic Coffee Maker",
      brand: "BrewMaster",
      price: 79.99,
      originalPrice: 129.99,
      currency: "USD",
      rating: 4.4,
      reviews: 187,
      description: "Programmable coffee maker with thermal carafe",
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500",
      images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500"],
      category: "sale",
      categories: ["sale", "homeliving"],
      tags: ["coffee", "maker", "sale", "appliance"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 140,
      stock: 35,
      createdAt: "2024-07-20",
      slug: "coffee-maker"
    },
    {
      id: 73,
      name: "Blender",
      title: "High-Speed Blender",
      brand: "BlendPro",
      price: 89.99,
      originalPrice: 149.99,
      currency: "USD",
      rating: 4.5,
      reviews: 189,
      description: "Professional-grade high-speed blender",
      image: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb?w=500",
      images: ["https://images.unsplash.com/photo-1553531889-56cc480ac5cb?w=500"],
      category: "sale",
      categories: ["sale", "homeliving"],
      tags: ["blender", "kitchen", "sale", "appliance"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 95,
      stock: 40,
      createdAt: "2024-08-25",
      slug: "high-speed-blender"
    },
    {
      id: 74,
      name: "Yoga Mat",
      title: "Premium Yoga Mat",
      brand: "YogaLife",
      price: 34.99,
      originalPrice: 59.99,
      currency: "USD",
      rating: 4.6,
      reviews: 267,
      description: "Non-slip premium thickness yoga mat",
      image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500",
      images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500"],
      category: "sale",
      categories: ["sale"],
      tags: ["yoga", "mat", "sale", "fitness"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 180,
      stock: 75,
      createdAt: "2024-09-10",
      slug: "yoga-mat"
    },
    {
      id: 75,
      name: "Desk Chair",
      title: "Ergonomic Desk Chair",
      brand: "OfficeComfort",
      price: 199.99,
      originalPrice: 299.99,
      currency: "USD",
      rating: 4.7,
      reviews: 156,
      description: "Adjustable ergonomic office desk chair",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500",
      images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500"],
      category: "sale",
      categories: ["sale", "homeliving"],
      tags: ["chair", "desk", "ergonomic", "sale"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 75,
      stock: 20,
      createdAt: "2024-08-05",
      slug: "desk-chair"
    },
    {
      id: 76,
      name: "Portable Speaker",
      title: "Bluetooth Portable Speaker",
      brand: "SoundGo",
      price: 59.99,
      originalPrice: 99.99,
      currency: "USD",
      rating: 4.4,
      reviews: 312,
      description: "Waterproof Bluetooth portable speaker",
      image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500",
      images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500"],
      category: "sale",
      categories: ["sale", "electronics"],
      tags: ["speaker", "bluetooth", "portable", "sale"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 210,
      stock: 60,
      createdAt: "2024-09-30",
      slug: "portable-speaker"
    },
    {
      id: 77,
      name: "Dumbbell Set",
      title: "Adjustable Dumbbell Set",
      brand: "FitGear",
      price: 149.99,
      originalPrice: 229.99,
      currency: "USD",
      rating: 4.8,
      reviews: 189,
      description: "Adjustable weight dumbbell set for home workouts",
      image: "https://images.unsplash.com/photo-1536922246289-88c42f957773?w=500",
      images: ["https://images.unsplash.com/photo-1536922246289-88c42f957773?w=500"],
      category: "sale",
      categories: ["sale"],
      tags: ["dumbbell", "fitness", "weights", "sale"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 85,
      stock: 30,
      createdAt: "2024-08-20",
      slug: "dumbbell-set"
    },
    {
      id: 78,
      name: "Cookware Set",
      title: "Non-Stick Cookware Set",
      brand: "KitchenPro",
      price: 129.99,
      originalPrice: 199.99,
      currency: "USD",
      rating: 4.6,
      reviews: 234,
      description: "10-piece non-stick cookware set",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500",
      images: ["https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500"],
      category: "sale",
      categories: ["sale", "homeliving"],
      tags: ["cookware", "kitchen", "nonstick", "sale"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 120,
      stock: 45,
      createdAt: "2024-07-25",
      slug: "cookware-set"
    },
    {
      id: 79,
      name: "Backpack",
      title: "Travel Backpack",
      brand: "TravelGear",
      price: 69.99,
      originalPrice: 119.99,
      currency: "USD",
      rating: 4.5,
      reviews: 178,
      description: "40L travel backpack with multiple compartments",
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
      images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500"],
      category: "sale",
      categories: ["sale", "accessories"],
      tags: ["backpack", "travel", "luggage", "sale"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 95,
      stock: 55,
      createdAt: "2024-09-15",
      slug: "travel-backpack"
    },
    {
      id: 80,
      name: "Desk Lamp",
      title: "LED Desk Lamp",
      brand: "LightWorks",
      price: 44.99,
      originalPrice: 79.99,
      currency: "USD",
      rating: 4.3,
      reviews: 156,
      description: "Adjustable LED desk lamp with multiple brightness levels",
      image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500",
      images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500"],
      category: "sale",
      categories: ["sale", "homeliving"],
      tags: ["lamp", "led", "desk", "sale"],
      onSale: true,
      isNew: false,
      isExclusive: false,
      sales: 140,
      stock: 65,
      createdAt: "2024-08-30",
      slug: "led-desk-lamp"
    }
  ];

  res.json(categoriesProducts);
});

module.exports = route;